# Generated by Django 5.0.2 on 2024-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_product_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(to="store.productcategory"),
        ),
    ]
