# Generated by Django 5.0.2 on 2024-04-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_productcategory_delete_category_product_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
