# Generated by Django 5.0.2 on 2024-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
